### ISSUE TITLE
CUDA fails on torchcodec==0.1.1+cu124 but is fine on 0.1.1+cu121

### ISSUE THREAD

**Issue by devanshrpandey** [pytorch/torchcodec#442]
### 🐛 Describe the bug

When trying to use the VideoDecoder with a random video with the standard pip install torchcodec version (and either CUDA version of torch 2.5.1), I get this:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/.local/share/uv/python/cpython-3.10.16-linux-x86_64-gnu/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/si/jupe/decode_test.py", line 31, in worker
    video = VideoDecoder(video_file, device="cuda")
  File "/home/ubuntu/si/.venv/lib/python3.10/site-packages/torchcodec/decoders/_video_decoder.py", line 96, in __init__
    core.add_video_stream(
  File "/home/ubuntu/si/.venv/lib/python3.10/site-packages/torch/_ops.py", line 716, in __call__
    return self._op(*args, **kwargs)
RuntimeError: Unsupported device: cuda
```

However, if I simply swap out torchcodec to `pip install torchcodec --extra-index-url https://download.pytorch.org/whl/cu121`, it does not have this error, either when I am using torch==2.5.1+cu121 or torch==2.5.1+cu124

Happy to put more effort into making a minimum repro but I suspect this is pervasive enough to easily reproduce.

### Versions

invariant:
python3.10.16
CUDA 12.6.85
torch2.5.1+cu121/cu124 (does not change behaviour)

**FAILS ON**
torchcodec==0.1.1+cu124

**SUCCEEDS ON**
torchcodec==0.1.1+cu121

Version info script fails with 
```
python collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "/home/ubuntu/si/collect_env.py", line 692, in <module>
    main()
  File "/home/ubuntu/si/collect_env.py", line 675, in main
    output = get_pretty_env_info()
  File "/home/ubuntu/si/collect_env.py", line 670, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/home/ubuntu/si/collect_env.py", line 495, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "/home/ubuntu/si/collect_env.py", line 450, in get_pip_packages
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by scotts** [comment]
Hi, @devanshrpandey! CUDA support is only available through the PyTorch index URL specified in our install instructions: https://github.com/pytorch/torchcodec?tab=readme-ov-file#installing-cuda-enabled-torchcodec

Reading this instructions, I now realize that fact is implied, but not explicitly stated. I've filed #445 to track making that change.

**Comment by devanshrpandey** [comment]
Ah, that's actually on me. I assumed that it would have the same behavior as torch/torchaudio/torchvision. Apologies!

**Comment by scotts** [comment]
@devanshrpandey, no, that's on us, as we mistakenly thought the pypi version should be CPU only. It was only when writing up #445 that I realized we were mistaken. We should change that for the next release. Regardless, we should be explicit in the README until then.

**Comment by scotts** [comment]
Closing as I believe the problem was a misunderstanding, which we can make more clear with #445.
